source "https://rubygems.org"

gem "byebug"
gem "capybara-screenshot"
gem "capybara-select2"
gem "docker-api", "~> 1.34"
gem "docker-compose", "~> 1.1"
gem "faker", "~> 1.9"
gem "govuk-lint", "~> 3.11.2"
gem "httparty"
gem "parallel_tests"
gem "plek", "~> 2.0"
gem "ptools"
gem "rake"
gem "rotp"
gem "rspec"
gem "rspec_junit_formatter"
