source "https://rubygems.org"

gem "byebug"
gem "capybara"
gem "capybara-screenshot"
gem "faker", "~> 1.6"
# gem "capybara-webkit"
gem "plek", "~> 2.0"
gem "poltergeist"
gem "rspec"
gem "rake"
gem "httparty"
